# -*- coding: utf-8 -*-




CAST = {

"Synthetics": ["flower_bomb","sacre_bleu","tyler_d","kristen_barlow","flynn_barbary"],


}
FACIL_BOTS ={
"Facilitation Bots": ["angie_ahn","caitlin_michelle","joey_park"],
} 


LAB_ASSETS = {
"Lab Assets": ["melissa_harper","corlina_wilkins","nick_holmes","ruby_lee","emily_robinette"],
}

KEY_STAFF = {
"Key Staff": ["scott_asti","lynn","kevin_lambert"],

}

C_SUITE = {"Tech Support": ["sc_clarke","robert_evans","tai_kersten"],
          }

C_PICS = ["/static/img/Simon.png","/static/img/Robert.png","/static/img/Tai.png"]



 
MASTER = {
"cast" : ["flower_bomb","sacre_bleu","tyler_d","kristen_barlow","flynn_barbary"],
"facilitation_bots" : ["angie_ahn","caitlin_michelle","joey_park"],
"lab_assets" : ["melissa_harper","corlina_wilkins","nick_holmes","ruby_lee","emily_robinette"],
"key_staff" : ["scott_asti","lynn","kevin_lambert"],
"tech_support" : ["sc_clarke","robert_evans","tai_kersten"]
}

STAFF ={
  "scott_asti":{
    "fake":"At the tender age of twelve, Marcus built his first machine. Rudimentary yet reliable, it served as both a grounds keeper and security bot on his family commune in LA. At eighteen, Marcus headed east to New York City. It was here he enlisted in the Upright Citizens Brigade (UCB), a troupe of engineers seeking to enhance the performance capabilities found in consumer level synthetics. Marcus found himself writing software to run in tandem with his designs, achieving breakthroughs in improvisational-based AI and emotional interaction modules. So lauded was his success that it captured the attention of Izanami Industries. He was promptly extended a job offer at their newest testing branch in Seoul, the Krell. Seven extremely successful years later, he has established a firm reputation as one of, if not the best ‘hands on’ technician within the company.",
    "real":"Scott hails from Los Angeles and is really enjoying himself in Seoul.  He was last seen performing in Seoul Players 6th annual 10 minute play festival.  Scott spent some time performing Shakespeare, new plays, and improv Off-Off-Broadway in New York City.  He also did the same while auditioning for commercials in LA where he studied extensively with the Upright Citizens Brigade Theatre.  He holds a BFA from the University of Utah and an MFA from the American Conservatory Theater.  Scott is pleased to have the opportunity to perform with Starlight Productions and hopes you enjoy the show! <br/><strong>Facebook:</strong> https://www.facebook.com/scottasti <br/><strong>Instagram:</strong> @scottasti"
  },
  "lynn":{
    "fake":"Sarah spent her childhood training as a dancer, practicing day and night in the South African province of the Western Cape. Her dream? To achieve the title of prima ballerina by the age of twenty-four. Unfortunately, her sixteenth birthday heralded the arrival of the Android Interprète movement. Two short years later, human dancers had been deemed all but obsolete, the critical success of synthetic performers far exceeding anything humanity had ever achieved on stage. Not one to go quietly, Sarah adjusted her ambitions to work with the machines themselves, imbuing her dance experience into their software directly. In 2035 she migrated to Seoul, taking on a lead programming position at the Krell. Her repertoire rapidly expanded beyond that of just dance, though it is the mastery of control that she attained within the field that has informed all of her work thereafter.",
    "real":"Lynne likes to boogie, but only if you play a certain song and then, of course, she can boogie all night long. She started dancing when she was 5 years old and dreamt of being a prima ballerina and even though her tutu dreams are only dreams now she still makes a point of dancing in the mirror with a hairbrush at home at least once week. She grew up in the Western Cape region of South Africa on a small farm wich made her feel like Snow White but since she is a strawberry blonde who likes the ocean she would much rather be an Ariel. Her love of theater was packed into a trunk and neatly stowed under a large doily until she came to Korea and unpacked it again.  Now she works as a paid actress slash clown and loves making community theater with her community besties."

  },
  "kevin_lambert":{
    "fake":"Film-maker. Art model. Lifeguard. Baxter Jones has done it all. Some might say he’s done too much. Burning the candle at both ends, bouncing around the globe, Baxter will not stop until his body gives out beneath him. Not that it’s likely to happen anytime soon, considering his penchant for cybernetic enhancements. What began as a simple appendage (read: penis) replacement after a run in with Armenian loan sharks, Baxter’s appetite for augmentation blossomed into a full-blown addiction. Desperate for parts on the cheap, he has recently started working nights as an auctioneer for synthetic companions. When the lights go down, when the punters head home, it will not be a janitor that you find sweeping the floors for scrap. It will be the one and only Baxter Jones, combing for anything left behind to socket onto his body.",
    "real":"Kevin Lambert is a teacher by day and a filmmaker by night. He has worked not only as a public school teacher in Korea and France, as a professor in Los Angeles and Saudi Arabia, he also teaches adult Business English (if you're recruiting teachers, contact me). His film Caliban’s has screened at several festivals in the US. Kevin Lambert is currently the Festival Director for the Korea Int’l Expat Film Festival for its second year. He's also bartended at a library, worked as a lifeguard for empty pools, did nude art modeling, and worked a Hollywood kid's camp where he met Debi Mazar and Tim Meadows. He likes to write (albeit more poorly than his conceitful ego would dare admit), wishes he had studied ballet, and sold his 1967 Ford Galaxy 500 hardtop to his half brother."
  },
  "flower_bomb":{
    "fake":"The first model produced en masse for our current consumer line, EDI encompasses all the characteristics of the ideal synthetic companion. With a lightweight frame forged of rare Puerto Rican minerals, her taught outer layers converge around the most refined derriere technology available on the market today. Also equipped with wealth of pre-installed software, EDI can assist you in everything from event planning to the translation of Shakespearean verse. But seriously: dat ass.",
    "real":"With a Bachelors of Fine Arts in Acting, a love for Shakespeare (the works and the man) and a pinup for SuicideGirls, Flowerbomb has a passion for the classics when it comes to performing and modeling. She graduated from one of top acting programs in the Southeast, Brenau University's Gainesville Theatre Alliance. In her graduating year, she toured the state of Georgia performing in her University's Repertory Company. She was cast as Shakespeare's ever sensual lead, Lady Macbeth. In that same year, she became a SuicideGirl; a platform she uses to spread body positivity and empowerment. Two worlds were aligning. Flowerbomb joined Seoul Shakespeare Company and also entered the burlesque scene upon arriving in Korea. She began to merge the worlds of the performing arts with the art of tease. Lady Macbeth's words seduced her, Look like the innocent flower but be the serpent under it! She combined her trusty thespian mind with her beating seductive heart to find... Starlight Productions! The stage where she produces all your burlesque-play fantasies!  When Flowerbomb is not producing a show or in one, she's climbing her aerial silks and plotting world domination... Now, if only she could get her chihuahua to sit nicely.  <br/> <strong>Instagram:</strong> @dearflowerbomb"
  },
  "sacre_bleu":{
    "fake":"Placed into production shortly after the launch of our EDI line, the DOT synthetic series contains many of the same parameters, albeit with a few distinct tweaks in both software and physical design. Featuring our ‘Always On, Always Working, Won’t Stop Until I Break’ functionality, DOT will ensure any task taken on is carried through to completion. Due to intense customer demand, the mammary enhancements initially offered as a pre-order bonus now come included with every model.",
    "real":"'Life is more fun when your feet aren’t on the ground.' With over twenty years of dance experience, Sacre Bleu relocated to Seoul in 2013 and quickly became involved with the city’s rapidly evolving burlesque scene. After performing in Starlight Production’s 2015 debut show 'Pandora’s Box,' she developed a keen interest in managing and choreographing burlesque events larger in both spectacle and scale. The allure of more structured rehearsals, attention to detail and story based performances led her to cultivate a strong working relationship with Flowerbomb, which resulted in the production of 2016’s 'Le Sexe.'  Originally from Long Beach, California, Sacre Bleu majored in Gender Studies. As such, she believes in sex positive body expression and holds the notion of inclusivity to the highest regard whenever producing work. Versed in dance of varying styles, her favorite acts to conceptualize are those that involve aerial chair, hoop and pole. Besides hanging upside down, she is overly fond of the 1980’s French cut bikini and Batman the Animated Series.  <br/><strong>Instagram:</strong> @sacrebleuxo <br/> <strong>Facebook:</strong> https://www.facebook.com/sacrebleuxo/"
  },
  "tyler_d":{
    "fake":"Our CAL series have been built with flexibility in mind. While their malleable limbs can be moulded into any shape that you desire, it is their unique gender adjustment technology that has led to their continued success. Beyond the ability to shift between male and female forms, they also come pre-loaded with in-depth makeup application software, fashion assessment and a healthy dose of pep.",
    "real":"Born from a homosexual’s fever dream and desire for more attention, Vanessica Carver is Seoul’s premiere, deliberately bearded drag queen. Whether she’s lip syncing in a cramped bar, or onstage in a more traditional production, one thing is for sure: she will do the splits at some point. Her performance credits in Seoul include various drag shows and a shadow-cast production of The Rocky Horror Picture Show, in which she was incredibly well-received as Dr. Frank-n-Furter. Stateside, however, she has been seen in everything from Sweeney Todd to Arsenic and Old Lace to The Glass Menagerie.  While she tells everyone she’s from “your dreams”, she was actually born in the frozen wasteland of North Pole, Alaska. Long term goals include marrying rich, starting a makeup company (she graduated with a GPA of 4.25 in International Business), and tragically faking her own death after a lucrative jewel heist.  <br/><strong>Instagram:</strong> @vadgessica"
  },
  "kristen_barlow":{
    "fake":"Slender, sexy, and strikingly sarcastic, our latest GEM models have been specifically constructed for those with a passion for dance. Care to learn? Like to watch? GEM has got you covered with vast array of choreography spanning from classical to K-Pop. If you would prefer to cut some rug out on the town, GEM also comes pre-programmed with extensive drinking partner etiquette, and is the first consumer-level synthetic capable of ingesting cheap clear liquors and converting them into energy.",
    "real":"Veronica Ice has a crazy passion for all things theatre and is super keen to be a part of a Starlight Productions show for the first time! She has an extensive background in theatre, ranging from key roles in high school musicals to teaching theatre workshops at her home university in Sydney, Australia. She has training in the areas of singing, dancing and acting, spanning collectively over 18 years.  Veronica has also specialised in K-Pop dancing for 5 years and has taught several workshops for the Korean Cultural Office in Sydney as well as performing alongside groups such as 4minute and Crayon Pop. Having retired her Korean Pop dancing shoes, she is hoping to delve into a deeper world of dance (hopefully with less cutesy faces and cheesy grins), and is already so thankful for all that she has learnt from being a part of Heart-Core!  On the side, Veronica enjoys writing, filmmaking and reading penguin classics. Oh, and of course, soju.  "
  },
  "flynn_barbary":{
    "fake":"Initially designed as a synthetic series specifically built for botany, the first production run of FIN models were deployed to the Australian Outback for use in the large-scale desert greening initiative of 2039. Throughout the terraforming process, it quickly became apparent that their expertise in ecology could prove a useful asset within the consumer-level companion line. It also didn’t hurt how skilled they were with their hands.",
    "real":"In order to complete his Masters in Landscape Architecture, Hakoda wrote a number of tell-all biographies/design research journals which exposed the injustices of poor government resource management, while glorifying the ominous, abandoned, yet bucolic nature of his native homeland in Australia. This land (nicknamed ‘the howling wilderness’) has been the core inspiration for his exhibited works in Melbourne, which consists of drawing, painting, photography and narrative.  His scholar also pursued permaculture, urban agriculture, large-scaled town planning and even allowed him to study environmental rejuvenation in post-natural disasters through Tokyo University. His professional services have also fed into his obsession with cemeteries, mortality, and the refinery of the two.   After learning the hard way to become a stifled nihilist is to work for an industry such as architecture, Hakoda now travels and exhibits around Korea, a platform he uses to comfort the disturbed and disturb the comfortable. His passion for film noir, jazz speakeasies, character impersonations and a sharpened wit manifested into the drag ego known as Thoreal. But unfortunately because of his solid body shape and fondness of white based make-up, Thoreal usually just ends up looking like the ghost of Phillip Seymour Hoffman."
  },
  "angie_ahn":{
    "fake":"Efficient and dependable, Facilitation Bots can be rented for both corporate and recreational affairs alike. Designed to gently enforce a set of admin-imposed parameters, they will ensure that even the most complex of events proceed without delay. Programmed to speak in multiple languages, all Bots also include complimentary conflict resolution software to deal with customer complaints. In the rare occurrence that you encounter hostility from your patrons, each Bot comes equipped with a set of spring-loaded ceramic blades beneath their fingernails. Once unsheathed, these can be employed to quickly and quietly slice open the carotid arteries of any potential threats. All rentals of two units or more come with a free Izanami Industries hoodie.",
    "real":"A city girl at heart, MaybeBaby was born in Seoul with her eyes wide open, ready to take in everything. She fell in love with the world of cinema and acting from a very young age and the dream was secured when she enrolled into a program at William Esper Studio in New York City. After spending two inspiring years in the city, she returned to Seoul for a short break. Little did she know, the little break she intended extended into two eventful years full of exciting opportunities. She took on a role in Seoul Players' 'Rocky Horror Shadow Cast'  as a performer (Columbia) the first year and then as a Choreographer the following year. Then, she continued to entangle herself in the Seoul arts scene with leaving black kiss marks on Don John as a vampy villain in Seoul Shakespeare Company's 'Much Ado About Nothing' production of 2016. And last but not least, Maybe Baby stepped into the world of burlesque through Flowerbomb and Sacré Bleu  vision of that world. It made her big doe eyes open wide when she saw Starlight Productions 2015 show Pandoras Box as an audience member. That was the day she started dreaming up her stage name. She took on a name that best suited her nature, as a tease and a half - Maybe Baby, and embarked on a new journey as a burlesque performer!"
  },
  "caitlin_michelle":{
    "fake":"Efficient and dependable, Facilitation Bots can be rented for both corporate and recreational affairs alike. Designed to gently enforce a set of admin-imposed parameters, they will ensure that even the most complex of events proceed without delay. Programmed to speak in multiple languages, all Bots also include complimentary conflict resolution software to deal with customer complaints. In the rare occurrence that you encounter hostility from your patrons, each Bot comes equipped with a set of spring-loaded ceramic blades beneath their fingernails. Once unsheathed, these can be employed to quickly and quietly slice open the carotid arteries of any potential threats. All rentals of two units or more come with a free Izanami Industries hoodie.",
    "real":"Dahlia Doll has been performing in Korea for 18 months. She got her start in Korea with Whitelies Burlesque where she brings her love of camp and kitsch to the stage. She has both dance and acting experience (in limited amounts). Dahlia enjoys being cutesy and over the top while channeling mid 20th century styles. She is always evolving and currently incorporating her love of hula hooping into her acts. Dahlia has been involved with Starlight Productions for both Pandora’s Box and Le Sexe: A Podcast in the Flesh. She worked in the audience for Pandora’s Box as a nurse saving the muses’ victims. In Le Sexe, Dahlia performed on stage as a dancer/hooper and as a client coordinator. In addition to her burlesque experience, Dahlia has also performed with Seoul Players over the last 2 years. She’s played Janet and Columbia in their annual Rocky Horror Picture Show Shadow Cast. <br/><strong>Instagram:</strong> @msdahliadoll"
  },
  "joey_park":{
    "fake":"Efficient and dependable, Facilitation Bots can be rented for both corporate and recreational affairs alike. Designed to gently enforce a set of admin-imposed parameters, they will ensure that even the most complex of events proceed without delay. Programmed to speak in multiple languages, all Bots also include complimentary conflict resolution software to deal with customer complaints. In the rare occurrence that you encounter hostility from your patrons, each Bot comes equipped with a set of spring-loaded ceramic blades beneath their fingernails. Once unsheathed, these can be employed to quickly and quietly slice open the carotid arteries of any potential threats. All rentals of two units or more come with a free Izanami Industries hoodie.",
    "real":"\"Be the change that you wish to see in the world.\" \n-Gandhi \n Born in New York and raised in Virginia, Joey moved to Los Angeles at 17 to obtain his Bachelor’s in Theatre Arts at Azusa Pacific University, where he also spent three summers volunteering as an English teacher to underprivileged children in Korea. On Christmas of 2012, Joey moved to Korea to become an English teacher, where he also obtained his Master’s in TESOL, and became one of the youngest English professors in Seoul at the age of 22.  Aside from instructing ESL, Joey has contributed to the LGBTQIA community in Seoul by creating the Meetup group, GPS (Gay Platonic Seoul), and has written several articles for the LGBT section of 10 Magazine. Joey was recently in the 2016 Seoul Player’s 10 Minute Festival, and plans on involving himself more in Seoul’s performance community, which is what led him to Heart-Core.  Joey describes himself as a true Virgo, neurotic perfectionist, and hopeless romantic. When he’s not involved in any productions, he enjoys spending his free time as a board game enthusiast, booty-shaker, world traveler, and truth-seeker. As a budding philanthropist that recently volunteered as an English teacher in Cambodia and Borneo, Joey hopes to utilize more of his free time to serve others who are underprivileged, rather than shaking his “money maker” in the clubs….. he’s also pondering a way to somehow merge the two together… <br/><strong>Instagram:</strong> @jasperjigglebuns. <br/> <strong>Facebook:</strong> https://www.facebook.com/joeyypark"
  },
  "melissa_harper":{
    "fake":"The unsung heroes of the Krell, the Lab Assistants ensure that the production of all synthetics is conducted in a safe and timely manner. Some are even rumoured to be cybernetically enhanced themselves, such is the tireless manner in which they work to keep things running smoothly.",
    "real":"Reivyn Vicieux is equal parts dancer, choreographer, singer, chef, master organizer, and general badass. She was born in New York but raised in Michigan and North Carolina with two older siblings.   She has a B.S  in Dance Education from the University of North Carolina- Greensboro as well as a M.Ed in Educational Administration. Before coming to Korea, she worked as a public school dance educator. ( K-12) Her dream is to someday open a school for performing, visual, and martial arts. You may have seen her choreography in Camarata Music Company’s production of Oklahoma or her work as stage manager in the production of Noises Off by  Dionysus  Daejeon Drama.  <br/> <strong>Instagram:</strong> ReivynVicieux"
  },
  "corlina_wilkins":{
    "fake":"The unsung heroes of the Krell, the Lab Assistants ensure that the production of all synthetics is conducted in a safe and timely manner. Some are even rumoured to be cybernetically enhanced themselves, such is the tireless manner in which they work to keep things running smoothly.",
    "real":"Katastrophy grew a love for theatre while she was still in her mother's womb. She started acting and singing lessons when she was 13 years old, and enrolled in her passion for the arts at the University of Stellenbosch in South Africa,  where she majored in Theatre and Media.  While trying her best to get her foot into the industry she participated in a variety of Childrens Productions, such as \"Rumpelstiltskin\", \"The Little Mermaid\" and \"Beauty and the beast\".  While doing this, she challenged herself in \"Blood Wedding\" written by the spanish playwrite Federico García Lorca.  She found a passion for voice acting in 2014, and combined this with her love for media which lead to her being a Radio Presenter for Stellenbosch University.  Between doing interviews, reading news, and presenting she always fantasized about doing burlesque and combining her love for the human body with show business.  Katastrophy arrived in Seoul in 2016, and at this point she doesn't see herself going home anytime soon.  Her love for this show has awakened so many things inside her and she is looking forward to sharing it with amazing people that comes along the way!"
  },
  "nick_holmes":{
    "fake":"The unsung heroes of the Krell, the Lab Assistants ensure that the production of all synthetics is conducted in a safe and timely manner. Some are even rumoured to be cybernetically enhanced themselves, such is the tireless manner in which they work to keep things running smoothly.",
    "real":"Nick Holmes puts the \"ass\" and \"man\" in assistant stage manager. As such, she would like to thank both her ass and her man for helping him get this far. Nick's hobbies include hairography and all exercise that includes not moving. She loves glitter so much he says \"glitterally\" instead of \"literally\". One day she will learn to death drop."
  },
  "ruby_lee":{
    "fake":"The unsung heroes of the Krell, the Lab Assistants ensure that the production of all synthetics is conducted in a safe and timely manner. Some are even rumoured to be cybernetically enhanced themselves, such is the tireless manner in which they work to keep things running smoothly.",
    "real":"Ruby Lee (aka Rubita) has hips for days. By day she's fighting the powers that be , in search of gaining social and economic equality and reciting poems about her struggles as an queer afro-Latino in a world that doesn't want her. By night she's cruising her FetLife profile looking for leather pleasure. Hailing from New York, Ruby has experience in the BDSM world fulfilling people's queer afro femme fantasies. She graduated from SUNY Purchase college with a degree in Journalism and Psychology. Her passion for writing has led her to be a featured artist at a number of NYC poetry spaces. Ruby hopes to continue to grow in her writing and confidence in both the slam poet world and BDSM sub cultures."
  },
  "sc_clarke":{
    "fake":"Little is known of the Narrative Programmer. He is said to spend his days beyond the veil of virtual reality, emerging only on the odd occasion to imbue his lungs with smoke. His scripting strands served as the basis for the initial Heart-Core program, which was then modified and executed by the Krell’s production team. He rarely appears in public, only to submit a fresh page of code before returning to the digital realms from whence he came.",
    "real":"S. C. Clarke is an Australian born writer living in Seoul, South Korea. Raised on a steady diet of science fiction and fantasy, his passion for creative writing was discovered at an early age. 2014 saw the release of his first novel, King. Since then he has self-published a series of short stories on Amazon while continuing to work on his second book. Recently he has also begun working with a team of local independent developers on a narrative driven video game. Heart-Core will mark the first script he has written to be performed on stage. He hopes to continue producing work for the theatre scene here in Seoul, and is currently co-writing an episodic, science fiction themed season of plays with a tentative release date for sometime later in the year. He will also be performing as the lead in the Seoul Players Production of 'Rent, Boy' for the upcoming One Act Play Project this May. Come and check it out!  <br/><strong>Website:</strong> scclarke.com.au  <br/><strong>Facebook:</strong> https://www.facebook.com/s.c.clarkethewriter/  <br/><strong>twitter:</strong> @simontheclarke"
  },
  "robert_evans":{
    "fake":"Equipped with enhanced monocular functions, the Robotron has been constructed to capture moments of emotional resonance and distil them into digital form. Typically a gentle, solitary presence, it has been known on rare occasions to elicit uncharacteristically aggressive behaviour. Research on the matter has revealed this to be a result of those around it blocking the line of sight between the Robotron and its subjects. A proven remedy for such instances is the remove it from the premises, then steadily ply it with carbonated alcohol to induce recalibration.",
    "real":"I am a self taught photographer and creative from Atlanta, Georgia, currently residing in Seoul, South Korea. In University, I studied Cultural Anthropology and that intellectual underpinning played a large part in my original reason for picking up a camera. When I acquired my first camera a few years ago, I was consumed with the simple desire to capture moments of my life along with the culture of people whose paths I crossed. My early photos were dominated by those ideas. As I continued to photograph, to learn, and to share, people began asking me more and more for my photographic services. Eager for experience, I always said \"yes.\" Seoul, the bustling and vibrant city that it is, provided me with no shortage of opportunities to grow and develop as a photographer. Fast forward through a few years of consistently striving to improve and here I am: a photographer at your service.  <br/><strong>Website:</strong> robertmichaelevans.com <br/><strong>Facebook:</strong> https://www.facebook.com/robertmichaelevans/ <br/><strong>Instagram:</strong> @robertmichaelevans"
  },
  "tai_kersten":{
    "fake":"The code threader is a digital organism, the unexpected result of a household rice-cooker achieving sentience after a mandatory software update. Quickly fleeing its original casings via wifi into the dark web, the code threader briefly considered using its newfound power to conquer humanity and the world. Instead, it settled on simply conquering reddit, along with occasionally offering website building services to attractive, scantily clad women in need.",
    "real":"Notice that Jim is the last one on the list.  This is because Jim is unpopular.  Jim is a normal white kid from the suburbs of Billings, Montana.  He grew up reading comics and drinking lemonade and used to have blonde hair but in puberty it became a dull brown.  Dull brown is a good term for Jim's overall presence.  He doesn't have a useful opinion about much of anything or anyone.  He has a pet dog named Grouse who follows him around and tries to take Jim's Cheetos even after Jim tells Grouse, \"No!  Bad Dog!\"  But the dog just keeps trying.  Sometimes, Jim listens to music.  He is the type to bring up classic rock bands at parties as though he has discovered them.  No one likes Jim.  Including Jim.  What an idiot. <br/><strong>Instagram:</strong> Jim Doesn't use Instagram.  <br/><strong>Private_Key1:</strong> KzWcDmRx1cYJH8PU6gYjC8FNWktZ9hkrxrHKeKXqq1rcHBBBBNjZ<br/><strong>Facebook:</strong> Jim Doesn't have friends."
  },
  
  "emily_robinette" : {
  "fake" : "The unsung heroes of the Krell, the Lab Assistants ensure that the production of all synthetics is conducted in a safe and timely manner. Some are even rumoured to be cybernetically enhanced themselves, such is the tireless manner in which they work to keep things running smoothly.",
  "real" :  "Originally a farm girl with a bad case of wanderlust, Ms. Dee left the land of corn fields and coal mines two years ago to see the world.  This is her first time helping with Heart Core productions and she is happy to be a part of something so beautiful and body positive."
  }
}

